name: CI/CD Production

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci-base.yml

  deploy-production:
    needs: ci
    uses: ./.github/workflows/deploy-netlify.yml
    with:
      production: true
    secrets:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_PRODUCTION }}
